---
- include_tasks: get-hostname-ec2-tag.yml
  when: hostname_from_ec2_Name_tag == true

- name: Use obtained _ec2_name_tag as the value of _hostname_to_use
  set_fact:
    _hostname_to_use: "{{ _ec2_name_tag | replace('.', '-') }}"
  when: _ec2_name_tag is defined

- name: Use server_hostname as the value of _hostname_to_use
  set_fact:
    _hostname_to_use: "{{ server_hostname | replace('.', '-') }}"
  when: _ec2_name_tag is not defined

- name: Hosts
  lineinfile:
    dest: /etc/hosts
    line: '127.0.0.1 {{ _hostname_to_use }}'
    state: present

- name: Set hostname to {{ _hostname_to_use }}
  hostname:
    name: "{{ _hostname_to_use }}"

- name: Check if cloud-init is installed
  command: "{{ hostname_cloud_init_check_command }}"
  ignore_errors: true
  register: hostname_cloud_init_status

- name: Configure cloudinit option on preserving hostname
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: "^preserve_hostname:[ \t]+false"
    line: "preserve_hostname: {{ hostname_cloud_init_preserve_hostname }}"
    state: present
  when: hostname_cloud_init_status.rc == 0
